id = "leetcode"
name = "LeetCode"
version = "0.1.1"
schema_version = 1
authors = ["Alec Zhou <alec1.zhou@gmail.com>"]
description = "Browse, solve, test and submit LeetCode problems in Zed"
repository = "https://github.com/azhou555/zed-leetcode"

[language_servers.leetcode]
name = "LeetCode"
languages = ["Markdown", "Python", "Rust", "C", "C++", "Java", "JavaScript", "TypeScript", "Go", "Ruby", "PHP", "Kotlin", "Swift", "Scala", "Dart", "CSharp", "Elixir", "Erlang", "Racket"]
